version: '3'

services:
  app:
    build:
      context: './'
      dockerfile: 'Dockerfile.dev'
    container_name: app
    environment:
      NODE_ENV: ${ENV:-dev}
    image: bahlinktri-app
    restart: on-failure
    ports:
      - '3000:3000'
    volumes:
      - './:/app:rw'
      - 'node_modules:/app/node_modules:Z'
volumes:
  node_modules:
